app = "mosquitto-50sggw"

[env]
  MOSQUITTO_CONFIG = "/mosquitto/config/mosquitto.conf"

[[services]]
  internal_port = 1883
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true

  [[services.ports]]
    port = 1883
    handlers = []

# Если нужен WebSocket
[[services]]
  internal_port = 9001
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true

  [[services.ports]]
    port = 9001
    handlers = []


